### ISSUE TITLE
Migrating Microsoft Identity Manager based application to Azure AD FS

### ISSUE THREAD

**Issue by edwardcampbellprojects** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1163]
I am attempting to migrate an ASP.NET WebForms application that uses MS Identity Manager to use an Azure Active Directory Federation Service, AADFS, for user Authentication and Authorization.  So far my conversion has succeeded at redirecting SignIn and SignOut to AADFS.  Within the application, it appears that an AuthenticationProtocolMessage.SetParameter is failing with a null parameter.

My questions are:
Is there general guidance for this type of conversion and is it feasible?,  (none found so far)
Has anyone completed such a migration with minimal, rather than wholesale, changes to the original source code?

Many thanks to anyone who can take the time to respond.

Edward Campbell

**Comment by brentschmaltz** [comment]
@edwardcampbellprojects I am not completely familiar with MS Identity Manager. Can you help me spin up?

**Comment by edwardcampbellprojects** [comment]
Hi Brent,

Thanks for your reply.  MIM is the successor to the Asp.NET Membership
system from several years ago.

This is a user/password based system with security hashes and password
hashes built in.

A better and more complete account can be found here:

https://docs.microsoft.com/en-us/microsoft-identity-manager/microsoft-identity-manager-2016


The issue I am having is that my org is converting to Azure AD FS and there
is a significant body of code that might need to be duplicated to get to a
complete integration.  I have tried the simple way of adding in an OWIN
Startup class and guiding users to our ADFS login.  The problem is that
there are many loose ends that may (or may not) depend on the presence of
FormsAuthentication cookies and other detritus from the previous embedded
code approach.

So I am just looking for any advice, expertise or examples of conversions
that have been done by others.

I did a few hours of searching and found no help.  This could, of course,
be a failure to specify the right search terms.

Thanks again for your reply.  Any comments or advice for futher research is
most appreciated.

Best Regards,

Ted Campbell

**Comment by brentschmaltz** [comment]
@edwardcampbellprojects got it.
@Tratcher can you help out here?

**Comment by Tratcher** [comment]
MIM looks like an AD add on? https://docs.microsoft.com/en-us/microsoft-identity-manager/
Looks like a replacement for FIM? https://oxfordcomputertraining.com/glossary/mim/

If they're just add ons then using WsFed or OpenIdConnect against Active Directory should still work. If this is Windows Server 2016 then use OpenIdConnect, otherwise WsFed.
https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/enabling-openid-connect-with-ad-fs

**Comment by brentschmaltz** [comment]
@edwardcampbellprojects can you let us know what in AuthenticationProtocolMessage.SetParameter is failing?

**Comment by edwardcampbellprojects** [comment]
Hi thanks for your email.  I was occupied by other fires lately.

I have traced the error to TokenValidationParameters.  The following code
fixes my immediate problem but the calling routine (BlogEngine.net 3.1)
still fails.

Here is the non-error producing adjustment (highlighted) in Startup.cs:

 public void ConfigureAuth(IAppBuilder app)
        {
            //***TC ADFS mod:
https://stackoverflow.com/questions/35621686/authentication-failed-because-the-remote-party-has-closed-the-transport-stream-e
            ServicePointManager.SecurityProtocol =
SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls12 |
SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;


app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);
            app.UseCookieAuthentication(new CookieAuthenticationOptions());

            var tokenValidationOptions = new
Microsoft.IdentityModel.Tokens.TokenValidationParameters()
            {
                ValidateIssuerSigningKey = false
            };

            var wsFedAuthOpts = new WsFederationAuthenticationOptions
            {
                TokenValidationParameters = tokenValidationOptions,

                MetadataAddress = adfsMetadata,
                Wtrealm = realm
            };
            app.UseWsFederationAuthentication(wsFedAuthOpts);
}

Prior to this adjustment, this is the error found in the windows event log

Event code: 3005

Event message: An unhandled exception has occurred.

Event time: 5/14/2019 8:07:59 AM

Event time (UTC): 5/14/2019 12:07:59 PM

Event ID: 498f3773a7d84e2fa5045d6bacc33859

Event sequence: 253

Event occurrence: 1

Event detail code: 0



Application information:

    Application domain: /0000000000000000000000000000

    Trust level: Full

    Application Virtual Path: /

    Application Path:
C:\_projects\.......................................\BlogEngine.NET\

    Machine name: XXXXXXXXXXXXXXXXXXXX



Process information:

    Process ID: 2348

    Process name: iisexpress.exe

    Account name: USDA\Edward.Campbell



Exception information:

    Exception type: ArgumentNullException

    Exception message: IDX10000: The parameter 'parameter' cannot be a
'null' or an empty object.

Parameter name: parameter

   at
Microsoft.IdentityModel.Protocols.AuthenticationProtocolMessage.SetParameter(String
parameter, String value)

   at
Microsoft.IdentityModel.Protocols.WsFederation.WsFederationMessage..ctor(IEnumerable`1
parameters)

   at
Microsoft.Owin.Security.WsFederation.WsFederationAuthenticationHandler.<AuthenticateCoreAsync>d__8.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)

   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)

   at
Microsoft.Owin.Security.Infrastructure.AuthenticationHandler.<BaseInitializeAsync>d__31.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)

   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)

   at
Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)

   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)

   at
Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)

   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)

   at
Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)

   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)

   at
Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)

   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)

   at
Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.<DoFinalWork>d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at
Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult
ar)

   at
Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult
ar)

   at
System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()

   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)

   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&
completedSynchronously)







Request information:

    Request URL:
https://localhost:44302/post.aspx?id=0225d7ce-58eb-4d5f-8290-38d6a28c3521

    Request path: /post.aspx

    User host address: ::1

    User: Edward L. Campbell

    Is authenticated: True

    Authentication Type: Cookies

    Thread account name: USDA\Edward.Campbell



Thread information:

    Thread ID: 12

    Thread account name: USDA\Edward.Campbell

    Is impersonating: False

    Stack trace:    at
Microsoft.IdentityModel.Protocols.AuthenticationProtocolMessage.SetParameter(String
parameter, String value)

   at
Microsoft.IdentityModel.Protocols.WsFederation.WsFederationMessage..ctor(IEnumerable`1
parameters)

   at
Microsoft.Owin.Security.WsFederation.WsFederationAuthenticationHandler.<AuthenticateCoreAsync>d__8.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)

   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)

   at
Microsoft.Owin.Security.Infrastructure.AuthenticationHandler.<BaseInitializeAsync>d__31.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)

   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)

   at
Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)

   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)

   at
Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)

   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)

   at
Microsoft.Owin.Security.Infrastructure.AuthenticationMiddleware`1.<Invoke>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)

   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)

   at
Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.<RunApp>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)

   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)

   at
Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.<DoFinalWork>d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at
Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult
ar)

   at
Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.EndFinalWork(IAsyncResult
ar)

   at
System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()

   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)

   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&
completedSynchronously)





Custom event details:



 Again, my apologies for the delay.  Thank you for your help and advice


Ted Campbell

**Comment by brentschmaltz** [comment]
@edwardcampbellprojects we made this fix in 5.5.0 that should fix this.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/972

**Comment by brentschmaltz** [comment]
@edwardcampbellprojects closing for now, let us know if you need anything.

**Comment by edwardcampbellprojects** [comment]
Hi Brent,

Thanks for keeping up with me.  I found an exception in jQuery-1.9.1 that
is stopping my code.  Although this helped remove 1 of the problems I was
seeing the problem still remains.   Thank you for your efforts.  I think
the locus of the problem is now definitely in my code and I am pursuing
that approach.

This was an example of good and skilled support.  Thanks again.

Ted

**Comment by brentschmaltz** [comment]
@edwardcampbellprojects let us know if you need anything.
