### ISSUE TITLE
System.Identitymodel.Tokens.JWT throws error for  Newtonsoft.Json 9.0.0

### ISSUE THREAD

**Issue by coreygrubbFHL** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#880]
Has anyone been made aware of the issue regarding System.Identitymodel.Tokens.JWT brought up in https://github.com/box/box-windows-sdk-v2/issues/426

the issue is best explained in the comment:

"I think I pinpointed the issue. If you look in the first post, there is a picture labeled "Picture of attempt without version 9.0.0:" which shows that System.Identitymodels.tokens.jwt.jsonextensions is what threw the exception. Upon analyzing the System.Identitymodels.tokens.jwt assembly, I took a closer look at the JsonExtensions type. I then looked for any reference to the Newtonsoft.Json assembly in the code for the JsonExtensions type and found the below code:

`static JsonExtensions() { JsonExtensions._serializer = new Serializer(JsonConvert.SerializeObject); JsonExtensions._deserializer = new Deserializer(JsonConvert.DeserializeObject); }`

I then did a comparison of the Newtonsoft.Json 9.0.0 and Newtonsoft.Json10.0.0 assemblies to see if I could find why the JsonExtensions type was throwing an exception when Newtonsoft.json version 9.0.0 was not imported into the powershell session. I found that the Deserializeobject and serializeobject methods seem to differ between the two assemblies in such a way that the later version of Newtonsoft.Json is not able to process the information which is being fed to it by System.Identitymodel.Tokens.JWT. I have attached the decompiled code for the "JSONconvert" type from both the 9.0.0 and 10.0.0 versions of Newtonsoft.json, and using winmerge to compare the text from the two files, there seems to be a substantial difference between the two. I hope this helps, and please let me know if you need me to do anything else."

I seem to be running into the exact same problem. Any help is greatly appreciated

**Comment by brentschmaltz** [comment]
@coreygrubbFHL what version are you using. The 5.x versions require 10.0.1

**Comment by whiggs** [comment]
What product are you asking for the version information of?   If it is powershell, then yes, I am using powershell 5.1.  This issue is still occurring, however, as the only way to bypass it is to import both versions of the assembly into the powershell session.  I would take a look at the original post that was referenced, as it has a lot of information and contains many pictures which show the problem.

**Comment by coreygrubbFHL** [comment]
Seems that this was resolved in the newest release of the Box windowns SDK. Thanks to everyone for their help.

**Comment by whiggs** [comment]
ACtually, it wasn't.  I mistakenly thought that was the case due to the fact the assemblies has already been imported.  I deleted the comment.  The issue is not resolved.  Sorry for the confusion.

**Comment by whiggs** [comment]
@brentschmaltz If you are looking for information concerning the assemblies that are used in the box windows sdk (at least as far as getting it to work in powershell is concerned), I created a custom nuget package that I host on [Myget](https://www.myget.org/feed/boxdependency/package/nuget/Box.Dependencies) which contains the box windows sdk and all of the dependency assemblies that were not already present in the GAC.  It is probably important to note that this was tested successfully on the latest version of Windows 10 enterprise (10.0.16299 N/A Build 16299).  I also have a [gist](https://gist.github.com/whiggs/5d9a9643982e15f8ddc61a21f5d46dbb) which uses the package management powershell module to register the myget repository and extract the assemblies to the local machine, and import them into the current powershell session.  It does some other things also like authenticating to box, but that portion is pretty useless without the json file containing the authentication info (more info [here](https://developer.box.com/docs/authentication-with-jwt)), but the gist linked above will extract the box windows sdk and dependent assemblies to "C:\programdata\boxlib."  Attached to this post is also a picture of the previously mentioned folder showing the extracted assemblies (names and versions).  As you can see from the picture (which is what prompted me to submit the ticket in the first place), both version 9.0.1 and 10.0.3 of the Newtonsoft.Json assembly need to imported into the current powershell session in order to successfully use the box windows sdk successfully, which is not only poor practice, but it is not supported in numerous IDE and ISE applications, which is a problem.  Let me know if you need anything else.  

![image](https://user-images.githubusercontent.com/11139575/36943984-fada421a-1f60-11e8-97ef-c3a238beca24.png)

**Comment by whiggs** [comment]
So the problem is actually resolved.  It turns out that there wasn't really an issue to begin with.  The resolution response explains it all:

It looks like this works in full .NET applications but not in PowerShell because the SDK's app.config file that binds any version of Newtonsoft.Json to the 10.x version that the SDK installs is not being loaded by PowerShell. Fundamentally, since you're going outside of the SDK's normal operation and loading the assemblies manually, you're going to have to ensure that the correct versions are installed and referenced. In the course of our investigation, we found some information about how to [make PowerShell load the app.config](https://stackoverflow.com/questions/17960/powershell-app-config), but weren't able to make it work in our environment.

I was able to get it to work by following the instructions in the link: just add '[appdomain]::CurrentDomain.SetData("APP_CONFIG_FILE", $configpath)' on the line before you import the assemblies and it works beautifully.  So no issue.  Can be closed.
